<?php

namespace Proxies\__CG__\Chat\ChatBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DatCreateclass extends \Chat\ChatBundle\Entity\DatCreateclass implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'auto_num', 'classname', 'classid', 'create_time');
        }

        return array('__isInitialized__', 'auto_num', 'classname', 'classid', 'create_time');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DatCreateclass $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAuto_num()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuto_num', array());

        return parent::getAuto_num();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuto_num($auto_num)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuto_num', array($auto_num));

        return parent::setAuto_num($auto_num);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassname', array());

        return parent::getClassname();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassname($classname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassname', array($classname));

        return parent::setClassname($classname);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassid', array());

        return parent::getClassid();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassid($classid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassid', array($classid));

        return parent::setClassid($classid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreate_time()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreate_time', array());

        return parent::getCreate_time();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreate_time($create_time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreate_time', array($create_time));

        return parent::setCreate_time($create_time);
    }

}
